server: default # servers that share the same value for this, share the booster data (e.g. Minigames)

settings:
  returnCommand: 'cc open menu' # This is the command for the arrow in the gui menu
  noBoostersIcon: PAPER
  noBoostersName: 'You have no boosters'
  noBoostersLore:
    - '&7u have no booster'
    - '&7u pleb'
    
  broadcast: true
  broadcastMessages:
    - '%player% has activated a %booster% booster' # for %duration%, but might be in the name anyway
  clickableTip: true  
  clickableTipMessage: 'Click &ehere &0to tip %player%'

boosters:
  mcmmo_x2:
    name: 'mcMMO X2 Booster (3 Hours)'
    type: 'mcmmo' # Boosters that share a queue
    duration: 180 # Duration in minutes
    tipping: false # Disable tipping for this booster
    offlineTipping: false # Only allow tipping if a player is online
    icon: DIAMOND_SWORD
    iconDamage: 0 # can remove this line if not used
    description:
      - '&7This is a booster'
      - '&7lolz'
    commandsOnStart:
      - 'booster command lulz'
      - 'another booster command lulz'
    commandsOnEnd:
      - 'booster command lulz'
      - 'booster command lulz'
    tipReward:
      - 'eco give %player% 100'
    tipMessages:
      - '&0Thank you for tipping &e%tippedPlayer%&0, you have recieved &e$100' # also %boosterName%, to use when running multiple boosters concurrently
    tippedReward:
      - 'eco give %player% 200'
    tipMessages:
      - '&e%tippingPlayer%&0 tipped you for &e$200'
