main: jdz.gcBoosters.GCBoosters
name: gcBoosters
version: 1.0
author: Jonodonozym
description: Platform for setting up, distributing, queuing and running boosters from other plugins.
depend: [JBU]
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  booster:
    description: commands for players
    aliases: [boosters]
  abooster:
    description: commands for admins
  tip: 
    description: tips a specified player
  tipAll:
    description: tips all possible boosters